### ISSUE TITLE
Fails when messages with no headers

### ISSUE THREAD

**Issue by mikeminutillo** [ParticularLabs/RoutingVisualization#5]
If you have messages in ServiceControl with no headers then the tool will fail when it tries to add them to the model. Something like this:

```
Reading messages from http://localhost:33333/storage
Message #6798
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RoutingVisualization.LogicalRoutingNodeStrategy.GetNodeId(EndpointDetails details) in C:\Net\RoutingVisualization-master\src\NodeStrategy.cs:line 57
   at RoutingVisualization.ModelBuilder.Accept(ProcessedMessage message) in C:\Net\RoutingVisualization-master\src\ModelBuilder.cs:line 23
   at RoutingVisualization.AllProcessedMessagesRoutedMessageSource.RegisterListener(Action`1 onNext) in C:\Net\RoutingVisualization-master\src\AllProcessedMessagesRoutedMessageSource.cs:line 24
   at RoutingVisualization.Program.Main(String[] args) in C:\Net\RoutingVisualization-master\src\Program.cs:line 22
```

**Comment by andreasohlund** [comment]
@fredricadell he're the issue for the bug you raised

**Comment by fredricadell** [comment]
I downloaded the sourcecode for the fix #5 and got an error again : 

```
Reading messages from http://localhost:33333/storage
Message #6640
Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at RoutingVisualization.ModelBuilder.Accept(ProcessedMessage message) in C:\N
et\RoutingVisualization-5-no-headers\src\ModelBuilder.cs:line 46
   at RoutingVisualization.AllProcessedMessagesRoutedMessageSource.RegisterListe
ner(Action`1 onNext) in C:\Net\RoutingVisualization-5-no-headers\src\AllProcesse
dMessagesRoutedMessageSource.cs:line 24
   at RoutingVisualization.Program.Main(String[] args) in C:\Net\RoutingVisualiz
ation-5-no-headers\src\Program.cs:line 22
```

**Comment by mikeminutillo** [comment]
@fredricadell - @andreasohlund mentioned that you had some blank messages in ServiceControl from a 3rd party integration point. In order to get ServiceControl to ingest an Audit message I have to give it a processing endpoint. If I leave off the Message Type I get the error you are encountering. I have made a change to fix that. It may result in a floating endpoint (as we have no meaningful data about how it's connected to anything. Can you please download the latest and try again?

**Comment by fredricadell** [comment]
I will give it a try!

**Comment by fredricadell** [comment]
Works like a charm! This is very good for analyzing the endpoint dependencys!!

**Comment by mikeminutillo** [comment]
@fredricadell I'd love to get some feedback on this. Also, if you're willing to share you diagram with me you can send it through to mike.minutillo@particular.net
